version: '3.8'

services:
  task-organizer:
    container_name: task-organizer
    image: task-organizer:latest
    build: .
    ports:
      - "8995:80"
    volumes:
      - ./:/usr/share/nginx/html
    restart: unless-stopped
